# version: "3.8"

services:
    backend:
        build: ./backend
        container_name: wishmaker-backend
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/wishmaker
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: wishmaker
            DB_USER: postgres
            DB_PASSWORD: postgres
            PORT: 8000
        ports:
            - "8000:8000"
        depends_on:
            postgres:
                condition: service_healthy
    frontend:
        build: ./frontend
        container_name: wishmaker-frontend
        environment:
            REACT_APP_API_URL: http://localhost:8000
            PORT: 3000
        ports:
            - "3000:3000"
        depends_on:
            - backend
    postgres:
        image: postgres:16-alpine
        container_name: wishmaker-db
        environment:
            POSTGRES_DB: wishmaker
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    postgres_data:
