export const RESERVED_USERNAMES: readonly string[] = [
    "admin",
    "root",
    "user",
    "test",
    "api",
    "www",
    "mail",
    "system",
    "support",
    "help",
    "about",
    "contact",
    "null",
    "undefined",
];
